/** Canonical audit event type strings — see docs/06,07,08,09 "Audit Events" sections. */
export enum AuditEventType {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  LOGIN = 'LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  SESSION_REVOKED = 'SESSION_REVOKED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_DISABLED = 'MFA_DISABLED',

  COMPANY_CREATED = 'COMPANY_CREATED',
  COMPANY_UPDATED = 'COMPANY_UPDATED',
  COMPANY_SUSPENDED = 'COMPANY_SUSPENDED',
  FEATURE_ENABLED = 'FEATURE_ENABLED',
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  BRANDING_UPDATED = 'BRANDING_UPDATED',
  AI_SETTINGS_CHANGED = 'AI_SETTINGS_CHANGED',

  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  POLICY_UPDATED = 'POLICY_UPDATED',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',

  // Document Management (doc 21) — Phase 3. OCR/AI Summary events are intentionally absent:
  // those features are out of scope per docs/DOMAIN_MODEL_PHASE3.md §3-4.
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_UPDATED = 'DOCUMENT_UPDATED',
  DOCUMENT_VERSION_CREATED = 'DOCUMENT_VERSION_CREATED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  DOCUMENT_ARCHIVED = 'DOCUMENT_ARCHIVED',
  DOCUMENT_DOWNLOADED = 'DOCUMENT_DOWNLOADED',

  // Core Trading Domain (docs 11/12/13) — Phase 4. AI recommendation events are intentionally
  // absent — AI Customer Profile/Product Expert/Pricing/Trading Assistant are seams, not
  // implemented, per docs/DOMAIN_MODEL_PHASE4.md.
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED = 'CUSTOMER_UPDATED',
  CUSTOMER_ARCHIVED = 'CUSTOMER_ARCHIVED',
  CONTACT_ADDED = 'CONTACT_ADDED',
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  CATEGORY_CREATED = 'CATEGORY_CREATED',
  PRICE_CHANGED = 'PRICE_CHANGED',
  RFQ_CREATED = 'RFQ_CREATED',
  QUOTATION_GENERATED = 'QUOTATION_GENERATED',
  QUOTATION_APPROVED = 'QUOTATION_APPROVED',
  QUOTATION_REJECTED = 'QUOTATION_REJECTED',
  QUOTATION_CONVERTED = 'QUOTATION_CONVERTED',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_UPDATED = 'ORDER_UPDATED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  PRICE_OVERRIDDEN = 'PRICE_OVERRIDDEN',

  // Inventory, Procurement & Finance (docs 14/16/17) — Phase 5.
  WAREHOUSE_CREATED = 'WAREHOUSE_CREATED',
  INVENTORY_RESERVED = 'INVENTORY_RESERVED',
  INVENTORY_RELEASED = 'INVENTORY_RELEASED',
  INVENTORY_COMMITTED = 'INVENTORY_COMMITTED',
  INVENTORY_REVERSED = 'INVENTORY_REVERSED',
  STOCK_ADJUSTED = 'STOCK_ADJUSTED',
  SUPPLIER_CREATED = 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  REQUISITION_CREATED = 'REQUISITION_CREATED',
  REQUISITION_APPROVED = 'REQUISITION_APPROVED',
  REQUISITION_REJECTED = 'REQUISITION_REJECTED',
  PURCHASE_ORDER_CREATED = 'PURCHASE_ORDER_CREATED',
  PURCHASE_ORDER_APPROVED = 'PURCHASE_ORDER_APPROVED',
  PURCHASE_ORDER_SENT = 'PURCHASE_ORDER_SENT',
  PURCHASE_ORDER_STATUS_CHANGED = 'PURCHASE_ORDER_STATUS_CHANGED',
  GOODS_RECEIPT_RECORDED = 'GOODS_RECEIPT_RECORDED',
  CHART_OF_ACCOUNT_CREATED = 'CHART_OF_ACCOUNT_CREATED',
  JOURNAL_POSTED = 'JOURNAL_POSTED',
  INVOICE_GENERATED = 'INVOICE_GENERATED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  SUPPLIER_BILL_CREATED = 'SUPPLIER_BILL_CREATED',

  // Task & Project Management (doc 25) — Phase 7a. No dedicated TaskActivity table — these
  // reuse the shared AuditLog, same precedent every business-module phase since Phase 4 has
  // followed. See docs/DOMAIN_MODEL_PHASE7.md.
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_REASSIGNED = 'TASK_REASSIGNED',
  AI_TASK_GENERATED = 'AI_TASK_GENERATED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  TIME_LOGGED = 'TIME_LOGGED',

  // Communication Management (doc 19) — Phase 7b. See docs/DOMAIN_MODEL_PHASE7.md.
  COMMS_THREAD_CREATED = 'COMMS_THREAD_CREATED',
  COMMS_MESSAGE_SENT = 'COMMS_MESSAGE_SENT',
  COMMS_PARTICIPANT_ADDED = 'COMMS_PARTICIPANT_ADDED',

  // Analytics & Business Intelligence (doc 20) — Phase 7c. See docs/DOMAIN_MODEL_PHASE7.md.
  REPORT_GENERATED = 'REPORT_GENERATED',
  REPORT_EXPORTED = 'REPORT_EXPORTED',
  FORECAST_GENERATED = 'FORECAST_GENERATED',
  AI_INSIGHT_GENERATED = 'AI_INSIGHT_GENERATED',
  SCHEDULED_REPORT_SENT = 'SCHEDULED_REPORT_SENT',

  // Human Resources (doc 15) — Phase 7d. See docs/DOMAIN_MODEL_PHASE7.md.
  EMPLOYEE_CREATED = 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED',
  ATTENDANCE_RECORDED = 'ATTENDANCE_RECORDED',
  LEAVE_REQUESTED = 'LEAVE_REQUESTED',
  LEAVE_APPROVED = 'LEAVE_APPROVED',
  LEAVE_REJECTED = 'LEAVE_REJECTED',
  PAYROLL_PROFILE_UPDATED = 'PAYROLL_PROFILE_UPDATED',
  PERFORMANCE_REVIEW_COMPLETED = 'PERFORMANCE_REVIEW_COMPLETED',
  ASSET_ASSIGNED = 'ASSET_ASSIGNED',
  ASSET_RETURNED = 'ASSET_RETURNED',
  TRAINING_RECORDED = 'TRAINING_RECORDED',
}

export interface AuditEntry {
  companyId: string | null;
  actorUserId: string | null;
  eventType: AuditEventType;
  entityType: string;
  entityId: string | null;
  before?: unknown;
  after?: unknown;
  ipAddress?: string | null;
}
