/**
 * Real consumption of `TaskGenerationRequested` (live Postgres + live Redis) — the actual bar
 * for "real" this phase, matching how Phase 6's e2e specs were the bar there. This event has
 * been published by `packages/rules-engine`'s `GENERATE_TASK` rule action since Phase 2 with
 * zero consumers until now — see docs/DOMAIN_MODEL_PHASE7.md §3. Publishes a real event through
 * the real `RedisStreamsEventBus`, runs the real subscriber
 * (`registerTaskGenerationRequestedSubscriber`), and asserts a real `Task` row is created with
 * the right `sourceModule`/`sourceEntityId` — not just that the code compiles.
 *
 * Requires DATABASE_URL and REDIS_URL to point at the stack in docker/docker-compose.yml.
 */
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { TenantContextStore } from '@platform/core';
import { getPrismaClient } from '@platform/database';
import {
  EVENT_TYPES,
  RedisStreamsEventBus,
  type TaskGenerationRequestedPayload,
} from '@platform/event-bus';
import { TaskService, registerTaskGenerationRequestedSubscriber } from '@modules/tasks';

const db = getPrismaClient();
const rawDb = new PrismaClient();

function withoutTenant<T>(fn: () => Promise<T>): Promise<T> {
  return TenantContextStore.run(
    { companyId: null, userId: null, sessionId: null, ipAddress: null, isPlatformActor: true },
    async () => await fn(),
  );
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

describe('Tasks: real TaskGenerationRequested consumption (live Postgres + Redis)', () => {
  let companyId: string;
  let unsubscribe: () => Promise<void>;

  beforeAll(async () => {
    const company = await withoutTenant(() =>
      rawDb.company.create({
        data: {
          companyCode: `TEST-TASKGEN-${Date.now()}`,
          legalName: 'Task Generation Test Co',
          country: 'US',
          timezone: 'UTC',
          currency: 'USD',
        },
      }),
    );
    companyId = company.id;

    const audit = { record: async () => {} };
    const taskService = new TaskService(db, audit);
    const eventBus = new RedisStreamsEventBus();
    unsubscribe = await registerTaskGenerationRequestedSubscriber(eventBus, taskService);

    const payload: TaskGenerationRequestedPayload = {
      ruleId: randomUUID(),
      companyId,
      title: 'Follow up on approved quotation',
      description: 'Auto-generated by a Rules Engine GENERATE_TASK action.',
      sourceModule: 'quotations',
      sourceEntityId: randomUUID(),
    };
    await eventBus.publish(
      EVENT_TYPES.TASK_GENERATION_REQUESTED,
      companyId,
      payload,
      '@platform/rules-engine',
    );

    // Poll until the real subscriber has actually created the Task row (bounded wait, same
    // pattern as packages/event-bus's own integration test).
    for (let i = 0; i < 20; i++) {
      const found = await withoutTenant(() =>
        rawDb.task.findFirst({ where: { companyId, sourceEntityId: payload.sourceEntityId } }),
      );
      if (found) break;
      await sleep(300);
    }
  }, 20000);

  afterAll(async () => {
    await unsubscribe();
    await withoutTenant(async () => {
      await rawDb.task.deleteMany({ where: { companyId } });
      await rawDb.auditLog.deleteMany({ where: { companyId } });
      await rawDb.company.delete({ where: { id: companyId } });
    });
    await rawDb.$disconnect();
  });

  it('creates a real Task row from a real published event, with the source linkage set and no assignee FK', async () => {
    const task = await withoutTenant(() => rawDb.task.findFirst({ where: { companyId } }));
    expect(task).not.toBeNull();
    expect(task!.title).toBe('Follow up on approved quotation');
    expect(task!.sourceModule).toBe('quotations');
    expect(task!.sourceEntityType).toBe('quotations');
    expect(task!.sourceEntityId).toBeTruthy();
    expect(task!.createdByUserId).toBeNull();
    expect(task!.status).toBe('BACKLOG');
  }, 20000);
});
